name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test

      - name: Set up ChromeDriver with WebDriverManager
        run: mvn io.github.bonigarcia:webdrivermanager-maven-plugin:latest-version:setup

      - name: Check Chromedriver Permissions
        run: |
          Get-ChildItem -Path C:\Selenium-ServeRest\chromedriver.exe | Format-List -Property Name, Mode
        shell: pwsh

      - name: Publish Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Publish Jacoco Coverage Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-reports
          path: target/site/jacoco/