name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chromedriver Path
        run: |
          if (Test-Path './chromedriver.exe') {
            Write-Host "Chromedriver exists at specified path."
          } else {
            Write-Error "Chromedriver not found at specified path."
          }
        shell: pwsh

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn test
        env:
          WEBDRIVER_CHROME_DRIVER: ./chromedriver.exe

      - name: Publish Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Publish Jacoco Coverage Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-reports
          path: target/site/jacoco/
